apiVersion: v1
kind: Namespace
metadata:
  name: amazon-clone
  labels:
    name: amazon-clone
    app: amazon-clone

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amazon-clone-sa
  namespace: amazon-clone
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: amazon-clone
  name: amazon-clone-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: amazon-clone-rolebinding
  namespace: amazon-clone
subjects:
- kind: ServiceAccount
  name: amazon-clone-sa
  namespace: amazon-clone
roleRef:
  kind: Role
  name: amazon-clone-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: amazon-clone-quota
  namespace: amazon-clone
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    requests.storage: 20Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: amazon-clone-limits
  namespace: amazon-clone
spec:
  limits:
  - default:
      cpu: "200m"
      memory: "256Mi"
      ephemeral-storage: "500Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
      ephemeral-storage: "100Mi"
    type: Container

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: amazon-clone-network-policy
  namespace: amazon-clone
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: amazon-clone
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: amazon-clone